apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    // Minimal main dependencies
    implementation 'com.palantir.safe-logging:logger'
    implementation 'com.palantir.safe-logging:preconditions'
    implementation 'com.palantir.safe-logging:safe-logging'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.awaitility:awaitility'
}

moduleJvmArgs {
    exports 'java.management/sun.management',
            'java.base/jdk.internal.platform',
            // Required for access to 'sun.net.InetAddressCachePolicy' for DNS cache TTL
            'java.base/sun.net'
}
